// src/Shared/footer.jsx
import { CContainer, CFooter,CLink,CRow,CCol } from "@coreui/react";
import { CForm,CFormInput,CButton } from "@coreui/react";

function Footer(){
    return(
        <>
        <CFooter>
            <CContainer>
                <CRow>
            <CCol>
                    <figure>
                        <img src="./src/assets/Logo.png" width="100" />
                    </figure>
                    <h4>Your Motivational Buddy</h4>
                <div>
                    <span> since 2020</span>
                </div>
                <br></br>
                <div>
                    <span>Powered by</span>
                    <CLink href="https://coreui.io"> CoreUI</CLink>
                </div>
            </CCol>
            <CCol>
                <h2>Stay Motivated!</h2>
            <CForm className="d-flex ms-auto">
                  <CFormInput type="search" className="me-2" placeholder="Enter Email Address" />
                  <CButton color="success" variant="outline">
                    Subscribe
                  </CButton>
                </CForm>
            </CCol>        
  <CCol>
    <h4>Socials</h4> 
    <p href="https://www.facebook.com/YourMotivationalBuddy/">Facebook</p>
    <p href="https://www.instagram.com/yourmotivationalbuddy/">Instagram</p>
    <p href="https://x.com/YMotivBuddy">Twitter/X</p>
    <p href="https://www.tiktok.com/@your_motivational_buddy">Tiktok</p>
    
  </CCol>
   </CRow>
    </CContainer>
        </CFooter>


        </>
    );
}

export default Footer

// src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { NewsletterFormComponent } from '../newsletter-form/newsletter-form.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [NewsletterFormComponent,CommonModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {

}

<footer class="footer p-10 bg-base-200 text-base-content">
  <aside>
    <figure>
      <img src='assets/media/brand/Your Motivational Buddy.png' width="50" />
    </figure>
    <p>Your Motivational Buddy<br>since 2020</p>
  </aside> 
  <nav>
    <h6 class="footer-title">Services</h6> 
    <a class="link link-hover">Quotes</a>
    <a class="link link-hover">Philosophy</a>
    <a class="link link-hover">Newsletter</a>
    <a class="link link-hover">Podcast</a>
  </nav> 
  <nav>
    <h6 class="footer-title">Support</h6> 
    <a class="link link-hover">About Us</a>
    <a class="link link-hover">Contact Us</a>
    <a class="link link-hover">Terms of use</a>
    <a class="link link-hover">Privacy Policy</a>
  </nav> 
  <nav>
    <h6 class="footer-title">Socials</h6> 
    <a class="link link-hover" href="https://www.facebook.com/YourMotivationalBuddy/">Facebook</a>
    <a class="link link-hover" href="https://www.instagram.com/yourmotivationalbuddy/">Instagram</a>
    <a class="link link-hover" href="https://x.com/YMotivBuddy">X</a>
    <a class="link link-hover" href="https://www.tiktok.com/@your_motivational_buddy">Tiktok</a>
  </nav> 
  <!--<app-newsletter-form />-->
</footer>
